spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/backend-database-dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG